### ISSUE TITLE
clemensv/mcp-servers

### ISSUE THREAD

**Issue by clemensv** [clemensv/xregistry-mcp#6]
Fill out the following yaml:

```yaml
repo: clemensv/mcp-servers
path: src/github
branch: main
mcpprovider: clemensv
server: gh1
```

whereby:
- **repo**: the path to the repo (e.g. org/repo) on Github or a full URL to a repo elsewhere
- **path**: the path in the repo where the `mcp.json` file can be found
- **branch**: the branch of the repo to look up
foo11
11
